<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" > 

<xacro:property name= "base_length" value="0.6" />
<xacro:property name= "base_width" value="0.4" />
<xacro:property name= "base_height" value="0.2" />
<xacro:property name= "wheel_radius" value="0.1" />
<xacro:property name= "wheel_length" value="0.05" />


<xacro:macro name="wheel_link" params="prefix" >

    <link name="${prefix}_wheel_link">

        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />

            </geometry>

            <origin xyz= "0 0 0" rpy="${pi/ 2.0} 0 0" />
            <material name="gray" />

        </visual>

        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />

            </geometry>

            <origin xyz= "0 0 0" rpy="${pi/ 2.0} 0 0" />
        </collision>



        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${2 * wheel_length}" xyz="0 0 0" rpy="${pi/ 2.0} 0 0" />
    </link>



</xacro:macro>

<!--  everything write on between these 2   --> 



<!--making the links   --> 
    <link name = "base_link">
        <visual>
            <geometry>
                <box size ="${base_length} ${base_width} ${base_height}" /> 
            </geometry>

            <origin xyz ="0 0 ${base_height/2.0}" rpy="0 0 0" />   <!--rpy = roll-x pitch-y yaw-z   --> 
            <material name="blue"/>
        </visual>
        <!-- defining the inertia of base  -->
        <xacro:box_inertia w="${base_width}" h="${base_height}" l="${2 * base_length}" m="5.0" xyz="0 0 ${base_height/2.0}" rpy="0 0 0"   />    
        
        <collision>
            <geometry>
                <box size ="${base_length} ${base_width} ${base_height}" /> 
            </geometry>
            <origin xyz ="0 0 ${base_height/2.0}" rpy="0 0 0" />   <!--rpy = roll-x pitch-y yaw-z   --> 

        </collision>
 
   <!-- box mass = 5 kg   -->

    </link>

    <!--to call the function  --> 
    
    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />



    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius/2.0}" />  <!-- in here wheel length is equal to radius of caster wheel  --> 
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />

            <material name="gray" />

        </visual>

        <collision>

           <geometry>
           
                <sphere radius="${wheel_radius/2.0}" />  <!-- in here wheel length is equal to radius of caster wheel  --> 
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />

        </collision>

        <xacro:sphere_inertia m="0.5" r="${2* wheel_radius/2.0}"  xyz="0 0 0" rpy="0 0 0" />

    </link>

    <link name="base_footprint" >
        <!-- empty link for lift up the robot form the ground --> 
    </link>

<!--making the joints  --> 
    <joint name="base_joint"  type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />

        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <joint name="base_right_wheel_joint"  type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />

        <origin xyz="-${base_length / 4.0} -${base_width/2.0 + wheel_length/2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint"  type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />

        <origin xyz="-${base_length / 4.0} ${base_width/2.0 + wheel_length/2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
 
    <joint name="base_caster_wheel_joint"  type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />

        <origin xyz="${base_length/3.0} 0 -${wheel_radius/2.0}" rpy="0 0 0" />
    </joint>



</robot>