joy_node:
    ros__parameters:
      device_id: 0
      deadzone: 0.05
      autorepeat_rate: 20.0

teleop_node:
  ros__parameters:

    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    sclae_linear_turbo:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_linear:
      yaw: 0.5
    sclae_linear_turbo:
      yaw: 1.0

    # enable_buttons: 6
    # enable_turbo_button: 7

    require_enable_button: false



    # move:
    #   type: topic
    #   interface_type: geometry_msgs/msg/TwistStamped
    #   topic_name: bumperbot_controller/cmd_vel

    #   deadman_buttons: [5]

    #   axis_mappings:
    #     twist-linear-x: 
    #       axis: 1
    #       scale: 1.0
    #       offset: 0
        
    #     twist-angular-z:
    #       axis: 3
    #       sclae: 1.0 
    #       offset: 0
      